### ISSUE TITLE
Utility for conditionally joining classNames together

### ISSUE THREAD

**Issue by dashed** [Stebalien/horrorshow-rs#7]
I had a need for something like https://github.com/JedWatson/classnames

I came up with the following macro:

```rust
macro_rules! classnames {
    
    // base cases
    
    ($name: expr) => (
        format!("{}", $name)
    );
    
    ($name:expr => $should_include:expr) => (
        if $should_include {
            format!("{}", $name)
        } else {
            format!("")
        }
    );
        
    // expansions
        
    ($name:expr, $($tail:tt)+) => {
        format!("{} {}", $name, classnames!($($tail)*))

    };
    
    ($name:expr => $should_include:expr, $($tail:tt)+) => {
        if $should_include {
            format!("{} {}", $name, classnames!($($tail)*))
        } else {
            classnames!($($tail)*)
        };
    };

}

// usage:
html!{
    
    div(class = classnames!("active" => true, "button-style")) {
        : "this is a button"
    }

    div(class = classnames!("active" => false, "button-style")) {
        : "this is a button"
    }
}
```

rust playground with examples: https://is.gd/e6Jahb

I just learned rust macros to make this; it can probably be refactored into something more nicer.

------

I'm wondering if this utility macro would be something worth adding to horrorshow. I can try to PR.

**Comment by Stebalien** [comment]
That definitely sounds useful.

Personally, I would call it something like `labels!` or `items!` because it can be used for more than class names.  I'd also use a guard syntax (`labels!("a", "b" if false, "c")`) as it makes it clear that the booleans are conditionals. Finally, the recursive calls to `format!` will have very poor performance. Instead, consider implementing the `Render` traits for some helper struct (you can even make this generic over items implementing `Render`); this will allow you to write directly to the template buffer instead of allocating intermediate strings.

At the end of the day, it should be possible to write:

```rust
    div(class = labels!("active" if false, "button-style", format_args!("nth-{}", i /* a number */)) {
        : "this is a button"
    }
```

and get (assuming i = 10):

```rust
<div class="button-style nth-10">this is a button</div>
```

**Comment by Stebalien** [comment]
If you need help with any of this, just ask. If you don't feel up for doing all of it, I can finish up anything you don't implement (i.e., partial PRs welcome).

**Comment by dashed** [comment]
The additional suggestions sounds good. 

I'm not totally clear on how to allocate `TemplateBuffer`.

**Comment by Stebalien** [comment]
You don't. Just implement `Render`, `RenderMut`, and `RenderOnce` (modeled after `Fn`, `FnMut`, and `FnOnce`) and a `TemplateBuffer` will get passed to you (it's an analog of `Display`'s `Formatter`).

**Comment by Stebalien** [comment]
Actually, you can probably just generate a closure wrapped in an `FnRenderer`. That is, `FnRenderer::new(|tmpl| { /* append appropriate labels to template */ })`.

**Comment by dashed** [comment]
Thanks. I created a PR attempt based on your suggestions.
